### PR TITLE
Fix ThemeProvider types in React 18

### PR DESCRIPTION
**Pull request by krystofrezac**
I added children to the ThemeProvider props type. In React 18 implicit children type was removed and needs to be typed explicitly.
[tweet with more info](https://twitter.com/reactjs/status/1512453230504124420)
[issue](https://github.com/callstack/react-theme-provider/issues/139)

### CODE REVIEW

**Comment by SergeyBakutov** [comment]
@krystofrezac in React 18, if a component has child components, you must specify the following: `ThemeProvider: React.ComponentType<React.PropsWithChildren<{ theme?: Theme }>>;` . Then Typescript will not show the error.

**Comment by krystofrezac** [comment]
@SergeyBakutov good point. I think that your suggestion is cleaner so I updated the code😃

**Comment by sorenhoyer** [comment]
👀

**Comment by s1gr1d** [comment]
Any updates on this?

**Comment by BohdanK-W32** [comment]
So?

**Comment by douglasjunior** [comment]
Fixed in #155 and released on version `3.0.9`

**Pull request closed without merging**
